// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwm8cNQN5VEKpuC25ZKIYCLes_6yZCNHg',
    appId: '1:88944840767:web:64681fb71a04f82e11a88a',
    messagingSenderId: '88944840767',
    projectId: 'remoteparentalcontrol-3fb74',
    authDomain: 'remoteparentalcontrol-3fb74.firebaseapp.com',
    storageBucket: 'remoteparentalcontrol-3fb74.appspot.com',
    measurementId: 'G-FWFW6LYB5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1g678BjYAg8A4rob6FAbC1wbaBlC8kU',
    appId: '1:88944840767:android:f3da0ebdfad4e74711a88a',
    messagingSenderId: '88944840767',
    projectId: 'remoteparentalcontrol-3fb74',
    storageBucket: 'remoteparentalcontrol-3fb74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqk_M6o0_fAPFIBYY1MokQk28FRVKgPFs',
    appId: '1:88944840767:ios:28598774805a9d0b11a88a',
    messagingSenderId: '88944840767',
    projectId: 'remoteparentalcontrol-3fb74',
    storageBucket: 'remoteparentalcontrol-3fb74.appspot.com',
    iosBundleId: 'com.example.remoteParentalControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqk_M6o0_fAPFIBYY1MokQk28FRVKgPFs',
    appId: '1:88944840767:ios:28598774805a9d0b11a88a',
    messagingSenderId: '88944840767',
    projectId: 'remoteparentalcontrol-3fb74',
    storageBucket: 'remoteparentalcontrol-3fb74.appspot.com',
    iosBundleId: 'com.example.remoteParentalControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwm8cNQN5VEKpuC25ZKIYCLes_6yZCNHg',
    appId: '1:88944840767:web:3975faca315f94da11a88a',
    messagingSenderId: '88944840767',
    projectId: 'remoteparentalcontrol-3fb74',
    authDomain: 'remoteparentalcontrol-3fb74.firebaseapp.com',
    storageBucket: 'remoteparentalcontrol-3fb74.appspot.com',
    measurementId: 'G-JVLXN251G7',
  );
}
